name: cosmography-2026
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyterlab
  - notebook
  - h5py
  - arviz
  - emcee
  - numba
  - pip
  - pip:
      - corner
